[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express", "@google-analytics/data", "google-auth-library"]
  node_bundler = "esbuild"
  included_files = ["package.json", "package-lock.json", "pnpm-lock.yaml"]
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
